matrix:
  fast_finish: true

image:
  - Visual Studio 2017

platform: x64

environment:
  matrix:
    - RuntimeURL: https://atom.io/download/atom-shell
      RuntimeName: iojs
      RuntimeVersion: v2.0.8
      NodeVersion: 8

  SLBuildDirectory: streamlabs-build
  SLGenerator: Visual Studio 15 2017 Win64
  SLDistributeDirectory: distribute
  SLFullDistributePath: $(SLBuildDirectory)\$(SLDistributeDirectory)
  SLArch: x64
  SignTool: C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe
  StreamlabsPfxSecret:
    secure: iZlMSWnmH5FQDpa+/0SgXIyvCobkElj2y5lu94Uo8VnTWHTeTC1/bpVkzsLreENocomvDB5ywsa3+QdathRp8A==
  StreamlabsSecret:
    secure: hr+VpykbGiCI5I0ltiqH667wh/YQx2Fi5SBLfkOWHSg=
  OBSVersion: 22.0.2

install:
  - ps: Install-Product node $env:NodeVersion x64
  - yarn install
  - git submodule update --init --recursive
  - ps: $env:SignedArtifact = "obs-studio-node-$(git describe --tags --abbrev=0)-$env:RuntimeName-$env:RuntimeVersion"
  - ps: $env:UnsignedArtifact = "obs-studio-node-us-$env:APPVEYOR_BUILD_NUMBER-$env:RuntimeName-$env:RuntimeVersion"

build_script:
  - cmd: ci\cmake-build.cmd

after_build:
  - copy "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\14.16.27012\x64\Microsoft.VC141.CRT\vcruntime140.dll" "%SLFullDistributePath%\obs-studio-node\"
  - copy "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\14.16.27012\x64\Microsoft.VC141.CRT\msvcp140.dll" "%SLFullDistributePath%\obs-studio-node\"
  - copy "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\14.16.27012\x64\Microsoft.VC141.CRT\concrt140.dll" "%SLFullDistributePath%\obs-studio-node\"
  - copy "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\ucrtbase.dll" "%SLFullDistributePath%\obs-studio-node\"
  - tar cvaf "%UnsignedArtifact%.tar.gz" -C "%SLFullDistributePath%" "obs-studio-node"

before_test:
  - cmd: cd tests\osn-tests
  - cmd: yarn install

test_script:
  - cmd: npm run test
  - cmd: cd ..\..

before_deploy:
  - nuget install secure-file -ExcludeVersion
  - ps: ci\win-signed-build.ps1
  - cmd: ci\copy-signed-binaries.cmd
  - tar cvaf "%SignedArtifact%.tar.gz" -C "%SLFullDistributePath%" "obs-studio-node"
  - ps: Push-AppveyorArtifact "$env:SignedArtifact.tar.gz"
  
  - appveyor DownloadFile "https://s3.amazonaws.com/getsentry-builds/getsentry/breakpad-tools/windows/breakpad-tools-windows.zip" -FileName "breakpadtools.zip"
  - 7z x "breakpadtools.zip" > nul
  - appveyor DownloadFile "https://github.com/getsentry/sentry-cli/releases/download/1.37.3/sentry-cli-Windows-i686.exe" -FileName "sentry-cli.exe"  
  
  # Transform our .pdb files into .sym and upload each of them to sentry using sentry-cli
  - cmd: ci\run-sentry-cli.cmd       

deploy:
  - provider: S3
    access_key_id:
      secure: C1Qzrf1+tbRDGmnXR6OpXwWuJr33d2JCVwn0KC/V7jw=
    secret_access_key:
      secure: dRSFQBZKAAVvDmZ0DOaoF54189P0b0mFCMSyTwn4eHZVBFdaET8C4Nb6VCJ4kT+a
    bucket: obsstudionodes3.streamlabs.com
    region: us-west-2
    set_public: true
    artifact: $(SignedArtifact).tar.gz
    on:
      appveyor_repo_tag: true

artifacts:
  - path: $(UnsignedArtifact).tar.gz
    name: Unsigned Aritfact

test: on